[project]
name = "resourcio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.2",
    "requests>=2.32.5",
    "uvicorn>=0.36.0",
]
